### ISSUE TITLE
Bizarre gene name inserted into PTHR10183 Pcalp

### ISSUE THREAD

**Issue by cmungall** [geneontology/touchup#22]
```
~/repos/go/gene-associations/submission/paint/PTHR10183 $ grep Term= PTHR10183.gaf  | cut -f10
Term=calpaindb_xref=PMID:19164769evidence=infer red from direct assay
Term=calpaindb_xref=PMID:19164769evidence=infer red from direct assay
```

col10 is the gene name field

This was introduced in r25025, 2015-04-08 (it would be great if touchup wrote it's version number in commits)

```
------------------------------------------------------------------------
r25025 | jenkins | 2015-04-08 08:51:46 -0700 (Wed, 08 Apr 2015) | 1 line

touchup via Jenkins
------------------------------------------------------------------------
r25003 | suzi | 2015-04-07 22:33:29 -0700 (Tue, 07 Apr 2015) | 1 line

undo touchup commit, rollback to revision r24949
------------------------------------------------------------------------
```

see http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/paint/PTHR10183/PTHR10183.gaf?r1=25003&r2=25025

or just do a 
```
$ svn diff -r 25003 PTHR10183.gaf  | grep Pcalp
```

The problem appears with touchup as this wasn't in the source GAF

**Comment by selewis** [comment]
Not sure how this crept in originally (it's the only case in 2900 trees), but once there it is sticky because it keeps getting this same full name back from GOlr the next time around. I added a hack for this particular case to cleave it out, but will have to keep an eye out for further weird ones. Nothing to do with touchup per se.
