### ISSUE TITLE
File structure change in PAINT2.0

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/touchup#27]
There are processes that rely on the files in the SVN, but they have been changed in 2.0.
1. File names changed, eg., .txt is now called .log, and .msa is now mia.
2. Files are missing, such as .exp, .attr, .sfan.

**Comment by selewis** [comment]
1. These suffixes (mia and tab) were modified to match those of the files as supplied by the PANTHER downloads. If PANTHER downloads is suffixing these with .mia (for example) then that is what PAINT will mimic.

2. .exp (snapshot of the experimental annotations) are now being saved again.

3. .sfan files are not used

4. the .txt change was to indicate more clearly (.txt could be anything) that this was the log of curator actions.

**Comment by huaiyumi** [comment]
It is OK to make changes like this. However there are downstream processes that use these files. I don't know other groups, but we have probably 5 different processes that rely on the PAINT svn files. I think any changes in file format, content and file names should be documented and notified to the community.

Thanks,

Huaiyu

**Comment by selewis** [comment]
Agreed.

Which particular files do you rely upon?

**Comment by huaiyumi** [comment]
Gaf, exp, txt.

Thanks

Huaiyu

**Comment by selewis** [comment]
.gaf is still there
.exp is now there
So easy to switch to .log?

**Comment by huaiyumi** [comment]
Gaf format is different (no IBAs for some files).
It is easy to change if I know they are renamed from .txt to .log. It is hard if I don't know. Also, when a fraction of the families use .log, while the remaining use .txt, it is harder to change in our process.

**Comment by krchristie** [comment]
Was this actually resolved? 

Monday (11/30/15), I was using 1.14 to try to update the notes for a family where the .gaf file was generated by splitting out annotations from a family that was split from Panther 9 to Panther 10 (see duplicate notes when splitting families #38 ). However, the notes aren’t loaded, presumably due to the .log extension on the notes file.

From my perspective, the minor advantage of the .log extension being a better name than .txt is vastly outweighed by the hassle that the name change causes in terms of things like having to change pipelines, and the fact that a given version of PAINT might not be able to open the notes file due to looking for the incorrect extension.

**Comment by selewis** [comment]
PAINT will open the .txt if the .log is unavailable.
Were you manually editing the file?
Call me on Skype and we can walk through this.

**Comment by krchristie** [comment]
I was using PAINT 1.14, trying to look at PTHR2343. At first I thought it wouldn't open anything for this family since it both of the two files it has, the .gaf and the .log files, were grayed out. However, I just went ahead and selected the .gaf file in the menu for opening an existing family, and it worked. However, the notes section in PAINT was blank.

I'm sure I could edit the .log file in emacs and save it. However, I wanted to open the family in PAINT with the existing annotations that were migrated, and then save it out so that PAINT would write out all of the files.
