### ISSUE TITLE
Regulation propagation rules

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#33]
1. Regulation of X should be allowed as evidence for X. 

2. It should also be possible to annotate both X and regulation of X on the same node. In this case, the annotations should be propagated (as IBA) to all descendants for both X and regulation of X. 

Example 1: regulation of development versus development
Example 2: phosphofructose kinase (the protein/gene product) both regulates and participates in glycolysis.

**Comment by selewis** [comment]
Still need to have a family ID, a term, and nodes for testing. Would you provide these please

**Comment by selewis** [comment]
The first is fixed. But still need a specific example for the second.

**Comment by marcfeuermann** [comment]
As an example: PTHR10006 (mucin-1): we have annotated to 'GO:0007155 - cell adhesion' but evidence is 'GO:0033629 - negative regulation of cell adhesion mediated by integrin'
Thanks

**Comment by selewis** [comment]
This isn't the fault or limitation of PAINT.

This is because there is no relationship in the ontology between 'GO:0007155 - cell adhesion' and 'GO:0033629 - negative regulation of cell adhesion mediated by integrin'

If it existed, PAINT would find it.

This needs to be submitted to the ontology request tracker. (which I'll do)

**Comment by selewis** [comment]
Arg, no github tracker yet.

I've added Melanie to the thread.

**Comment by cmungall** [comment]
The ontology is complete here:

<img width="827" alt="screen shot 2015-12-08 at 1 12 42 pm" src="https://cloud.githubusercontent.com/assets/50745/11679349/608d1676-9e50-11e5-9dc2-dd6c2f75b566.png">

**Comment by cmungall** [comment]
@pgaudet not sure I follow example 2. Are you proposing these all-some links be added to the ontology? In general functions are parts of different processes in different contexts. The ontology would only have has-parts, and part-ofs in LEGO models (contextual / instances)

**Comment by selewis** [comment]
Ah, now I see. Two comments!

First of all, apologies. My mistake. I looked at the same graph Chris included above, and simply did not see cell adhesion (GO:0007155) in the graph. Just blind! So apologies for that.

Second, thanks to Marc's example, I now understand the dilemma. The bug is a user interface issue. I had changed the logic to allow (but flag) annotations derived from child regulate terms. Tested it too. Everything working perfectly. But, I was testing using touchup not the PAINT ui. So I didn't notice that the regulates parental terms were not being added to the matrix term column menus. The problem wasn't that using these wasn't possible, but that the term wasn't being presented.

Less than a one-line fix.

That said, I hesitate to release the current code I'm working on because other things are (intentionally) broken. Will next week be okay?

**Comment by pgaudet** [comment]
Hi Suzi, 

Take your time, let us know when this is ready to test ! 

Thanks, 
Pascale

**Comment by selewis** [comment]
Ready for testing (should have said something earlier, it's been there since January)

**Comment by pgaudet** [comment]
OK yes, this is working :)

**Comment by pgaudet** [comment]
Hello, 

This was wonrking in a previous version of PAINT - I was able to annotate BOTH cell adhesion (GO:0007155) and negative regulation of cell adhesion mediated by integrin (GO:0033629). This is not working on PAINT2.0 from March 14,2016. 

Suzi, can you please have a look ?

**Comment by selewis** [comment]
I just tried this (PTHR10006) and it worked for me, but perhaps it was different nodes? I think we need to screen share to sort this out, because I can't duplicate the problem.
