### ISSUE TITLE
TAIR ID not recognized ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#52]
Hello, 

I have annotated PTHR11136 earlier today (although I loaded it on Friday). Today I re-loaded it, and I get the following error message: 

## Annotations that have been removed.
20160606: cellular organisms_PTN001340249 to mitochondrial matrix (GO:0005759)  using [TAIR:locus:2100048, TAIR:locus:2177916] - lacks supporting evidence

It looks like the TAIR IDs are causing problems. There is *at least* one TAIR protein in the tree that has an annotation to mitochondrial matrix (http://www.arabidopsis.org/servlets/TairObject?type=locus&name=AT3G10160)

What worries me is that touch up would have stripped this annotation, wouldn't it ? I don't understand why I see different data from one load to the next. 

Thanks, 
Pascale

**Comment by selewis** [comment]
Hi Pascal, checking up on things today. When I load your family the annotation to mitochrondrial matrix remains intact and no warning is issued.

I know Huaiyu was messing about a bit with the TAIR IDs on the PANTHER side, but don't know whether or not that has anything at all to do with this.

In other news, the links out to TAIR are now working. They require the "name" (AT3G10160) rather than the gene ID (locus:2078936). It is the latter that TAIR uses when in submits its GAF files to GO. TAIR's system is (ahem) unique shall we say...

**Comment by huaiyumi** [comment]
That is what reference proteome uses for TAIR. Not sure why.

Huaiyu
