### ISSUE TITLE
Ensembl links not working in PAINT 2.0-beta19

### ISSUE THREAD

**Issue by pgaudet** [geneontology/touchup#53]
Hello,

In PAINT 2.0-beta19, the links to ensemble are not working. For example, in PTHR23509, the link 
http://www.ensembl.org/Populus_trichocarpa/Gene/Summary?g=POPTR_0013s10490
gives a 404 error in ensembl. 

Thanks, Pascale

**Comment by krchristie** [comment]
Hi,

I'm working on PTHR16056 right now, and looking at several different links to ENSEMBL, it looks to me like some do work while others do not. From the bottom of the tree, half way down in the RMDN1 clade, these ones work:

<pre>
ID in PAINT         resulting web page
ENSPTRG00000020396      http://uswest.ensembl.org/Pan_troglodytes/Gene/Summary?g=ENSPTRG00000020396;r=8:84576089-84611066;t=ENSPTRT00000037749
ENSMMUG00000006307      http://uswest.ensembl.org/Macaca_mulatta/Gene/Summary?g=ENSMMUG00000006307;r=8:89050974-89085411;t=ENSMMUT00000008837
ENSMODG00000008100      http://uswest.ensembl.org/Monodelphis_domestica/Gene/Summary?g=ENSMODG00000008100;r=3:347516324-347559832;t=ENSMODT00000010267
ENSOANG00000002040      http://uswest.ensembl.org/Ornithorhynchus_anatinus/Gene/Summary?g=ENSOANG00000002040;r=Ultra39:1583198-1609556;t=ENSOANT00000003235
ENSACAG00000009774      http://uswest.ensembl.org/Anolis_carolinensis/Gene/Summary?g=ENSACAG00000009774;r=4:22799411-22814259;t=ENSACAT00000009831
ENSGALG00000022790      http://uswest.ensembl.org/Gallus_gallus/Gene/Summary?g=ENSGALG00000022790;r=2:122912147-122925502;t=ENSGALT00000036639
ENSCING00000019878      http://uswest.ensembl.org/Ciona_intestinalis/Gene/Summary?g=ENSCING00000019878;r=4:559202-561762;t=ENSCINT00000034420
ENSCING00000020525      http://uswest.ensembl.org/Ciona_intestinalis/Gene/Summary?g=ENSCING00000020525;r=1:7013244-7014137;t=ENSCINT00000037137
</pre>

These ones produce a 404 error:
<pre>
ID in PAINT        resulting web page
ISCW002532          http://uswest.ensembl.org/Ixodes_scapularis/Gene/Summary?g=ISCW002532
ISCW022261          http://uswest.ensembl.org/Ixodes_scapularis/Gene/Summary?g=ISCW022261

PITG_16317          http://uswest.ensembl.org/Phytophthora_infestans/Gene/Summary?g=PITG_16317
PITG_17263          http://uswest.ensembl.org/Phytophthora_infestans/Gene/Summary?g=PITG_17263
Tb10.61.0320        http://uswest.ensembl.org/Trypanosoma_brucei/Gene/Summary?g=Tb10.61.0320
LmjF.19.1400        http://uswest.ensembl.org/Leishmania_major/Gene/Summary?g=LmjF.19.1400
GL50803_14322       http://uswest.ensembl.org/Giardia_intestinalis/Gene/Summary?g=GL50803_14322
</pre>

-Karen

**Comment by selewis** [comment]
The challenge with composing the Ensembl links is that it is not enough to merely have the ID. You also have to figure out exactly what Genus_species string to use. But that doesn't seem to be the issue here.

Rather, these IDs are not Ensembl gene IDs at all (no wonder they don't work) but some other sort altogether. What I've done is that if the id form doesn't match the form that that db (e.g. PITG_16317 is not an Ensembl  ID) then it defaults to using the uniprot id and database. There are also legitimate Ensembl IDs, like CADANIAT00006377, but I would have to hard code in the fact that this link is specifically to the fungi Ensembl database (URL http://fungi.ensembl.org/Aspergillus_nidulans/Transcript/Summary?db=core;g=CADANIAG00006377;r=III:3131723-3133068;t=CADANIAT00006377) which is too unreliable. There are links from UniProt to Ensembl so I think we're okay on this now. 

Look for release V2.20
